command: [
  "uvicorn",
  "api.app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_CATALOG"
    value: "app_data"
  - name: "DATABRICKS_SCHEMA"
    value: "app_ucsak"
