command: [
  "uvicorn",
  "api.app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000"
]

env:
  - name: "DATABASE_TYPE"
    value: "postgres"
  - name: "POSTGRES_HOST"
    value: "instance-33607cf0-86c1-4306-a5c3-2464761fa328.database.cloud.databricks.com"
  - name: "POSTGRES_PORT"
    value: "5432"
  - name: "POSTGRES_USER"
    value: "rucsak_app_user"
  - name: "POSTGRES_PASSWORD"
    valueFrom: "db_password"
  - name: "POSTGRES_DB"
    value: "app_ucsak"

  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_CATALOG"
    value: "app_data"
  - name: "DATABRICKS_SCHEMA"
    value: "app_ucsak"
  - name: "DATABRICKS_VOLUME"
    value: "app_files"

  - name: "APP_DEMO_MODE"
    value: "true"

  - name: "APP_ADMIN_DEFAULT_GROUPS"
    value: '["admins"]'
  - name: "APP_AUDIT_LOG_DIR"
    value: "audit_logs"
    #value: "/Volumes/${workspace.env.DATABRICKS_CATALOG}/${workspace.env.DATABRICKS_SCHEMA}/${workspace.env.DATABRICKS_VOLUME}/audit_logs"
  