command: [
  "uvicorn",
  "api.app:app",
  "--host",
  "0.0.0.0",
  "--port",
  "8000"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_CATALOG"
    value: "app_data"
  - name: "DATABRICKS_SCHEMA"
    value: "app_ucsak"
  - name: "DATABRICKS_VOLUME"
    value: "app_files"
  - name: "APP_DEMO_MODE"
    value: "true"
  - name: "APP_ADMIN_DEFAULT_GROUPS"
    value: '["admins"]'
  - name: "APP_AUDIT_LOG_DIR"
    value: "/Volumes/${workspace.env.DATABRICKS_CATALOG}/${workspace.env.DATABRICKS_SCHEMA}/${workspace.env.DATABRICKS_VOLUME}/audit_logs"